---
title: "supervised_ml_cars"
format: html
---
```{r}
if (!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)
if (!require("usethis")) install.packages("usethis")
library(usethis)
if (!require("tidymodels")) install.packages("tidymodels")
library(tidymodels)
```
## Visualize

```{r}
cars2018 <- read_csv("data/cars2018.csv")

# Print the cars2018 object
glimpse(cars2018)

# Plot the histogram
cars2018 %>%
  ggplot(aes(x = mpg)) +
  geom_histogram(bins = 25) +
  labs(
    x = "Fuel efficiency (mpg)",
    y = "Number of cars"
  )
```

## Build a simple regression model:
```{r}
# Deselect the 2 columns to create cars_vars. Individual identifiers
car_vars <- cars2018 %>%
  select(-model, -model_index)

# Fit a linear model
fit_all <- lm(mpg ~ ., data = car_vars)

# Print the summary of the model
summary(fit_all)
```

## Splitting data: Training and testing datasets.

(Tidymodels)
```{r}
car_split <- car_vars %>%
    initial_split(prop = 0.8,
                  strata = aspiration)

car_train <- training(car_split)
car_test <- testing(car_split)
```


## Training model.
```{r}
## a linear regression model specification
lm_mod <- linear_reg() %>%
    set_engine("lm")

lm_fit <- lm_mod %>%
    fit(log(mpg) ~ ., 
        data = car_train)

## a random forest model specification
rf_mod <- rand_forest() %>%
    set_mode("regression") %>%
    set_engine("randomForest")

fit_rf <- rf_mod %>%
    fit(log(mpg) ~ ., 
        data = car_train)   
```


